GET http://localhost:5000


### Check server status


GET http://localhost:5000/api


### Get all registered users
GET http://localhost:5000/api/users


### Get all closed complaints
GET http://localhost:5000/api/complaints


### Get all closed complaints of a user
GET http://localhost:5000/api/complaints?user=9zmyLUwecoN6XlcZVAfON1tSLJd2


### Get closed complaint by id
GET http://localhost:5000/api/complaints/5e6a2c0b06be6032f89d466f


### Get all complaints
GET http://localhost:5000/api/complaints?firebase=true


### Get complaint by id
GET http://localhost:5000/api/complaints/h3l1wsoCgzN5l2ksBCFP322zGc03?firebase=true


### Change status of complaint
CHECKOUT http://localhost:5000/api/complaints/h3l1wsoCgzN5l2ksBCFP322zGc03


### Delete a complaint (mark as fake)
DELETE http://localhost:5000/api/complaints/DQsxMYvWhmbgEGXRnSwknxlncp43


### Send Notification for new complaint
NOTIFY http://localhost:5000/api/complaints


### Send Notification for new complaint
GET http://localhost:5000/api/complaints?notify=true


### Get all Fake Complaints or Deleted Complaints
GET http://localhost:5000/api/complaints?fake=true


### Get all Fake Complaints or Deleted Complaints of a user
GET http://localhost:5000/api/complaints?fake=true&user=DQsxMYvWhmbgEGXRnSwknxlncp43


### Get Fake Complaint by id or Deleted Complaints
GET http://localhost:5000/api/complaints/5e6dd056508ba12ec413475e?fake=true


### Send Whatsapp message notification for complaint
POST http://localhost:5000/api/whatsapp
Content-Type: application/json

{
    "phoneNumber": "9530077351",
    "complaintId": "DQsxMYvWhmbgEGXRnSwknxlncp43"
}


###
